Repository AY1920S1-CS2103T-F11-2/main, pull requests merged in 2019-11, with the labels that each got.

#181 Implement efficient Undo/Redo
  docs/UserGuide.adoc
  src/main/java/io/xpire/logic/LogicManager.java
  src/main/java/io/xpire/logic/commands/AddCommand.java
  src/main/java/io/xpire/logic/commands/CheckCommand.java
  src/main/java/io/xpire/logic/commands/ClearCommand.java
  src/main/java/io/xpire/logic/commands/Command.java
  src/main/java/io/xpire/logic/commands/DeleteCommand.java
  src/main/java/io/xpire/logic/commands/ExitCommand.java
  src/main/java/io/xpire/logic/commands/ExportCommand.java
  src/main/java/io/xpire/logic/commands/HelpCommand.java
  src/main/java/io/xpire/logic/commands/RedoCommand.java
  src/main/java/io/xpire/logic/commands/SearchCommand.java
  src/main/java/io/xpire/logic/commands/SetReminderCommand.java
  src/main/java/io/xpire/logic/commands/ShiftToMainCommand.java
  src/main/java/io/xpire/logic/commands/ShiftToReplenishCommand.java
  src/main/java/io/xpire/logic/commands/SortCommand.java
  src/main/java/io/xpire/logic/commands/TagCommand.java
  src/main/java/io/xpire/logic/commands/UndoCommand.java
  src/main/java/io/xpire/logic/commands/ViewCommand.java
  src/main/java/io/xpire/logic/parser/CheckCommandParser.java
  src/main/java/io/xpire/logic/parser/XpireParser.java
  src/main/java/io/xpire/model/CloneModel.java
  src/main/java/io/xpire/model/Model.java
  src/main/java/io/xpire/model/ModelManager.java
  src/main/java/io/xpire/model/Xpire.java
  src/main/java/io/xpire/model/history/CommandHistory.java
  src/main/java/io/xpire/model/item/SortedUniqueXpireItemList.java
  src/main/java/io/xpire/model/item/sort/XpireMethodOfSorting.java
  src/main/java/io/xpire/model/state/FilteredState.java
  src/main/java/io/xpire/model/state/ModifiedState.java
  src/main/java/io/xpire/model/state/StackManager.java
  src/main/java/io/xpire/model/state/State.java
  src/main/java/io/xpire/model/state/StateChecker.java
  src/main/java/io/xpire/model/state/StateManager.java
  src/main/java/io/xpire/storage/JsonAdaptedItem.java
  src/main/java/io/xpire/storage/JsonAdaptedXpireItem.java
  src/test/java/io/xpire/logic/commands/AddCommandTest.java
  src/test/java/io/xpire/logic/commands/CheckCommandTest.java
  src/test/java/io/xpire/logic/commands/CommandTestUtil.java
  src/test/java/io/xpire/logic/commands/SetReminderCommandTest.java
  src/test/java/io/xpire/logic/parser/CheckCommandParserTest.java
Labels: priority.High

#186 Resolve bugs related to expiry dates of items
  docs/UserGuide.adoc
  src/main/java/io/xpire/commons/util/DateUtil.java
  src/main/java/io/xpire/logic/parser/ParserUtil.java
  src/main/java/io/xpire/logic/parser/ReplenishParser.java
  src/main/java/io/xpire/model/item/ExpiryDate.java
  src/main/java/io/xpire/storage/JsonAdaptedXpireItem.java
  src/main/java/io/xpire/ui/ItemCard.java
  src/test/java/io/xpire/model/item/ExpiringSoonPredicateTest.java
  src/test/java/io/xpire/model/item/ReminderThresholdExceededPredicateTest.java
  src/test/java/io/xpire/testutil/TypicalItems.java
  src/test/java/io/xpire/testutil/TypicalItemsFields.java
Labels: status.ReviewRequested

#194 Refactor ModelManager and Model API
  build.gradle
  src/main/java/io/xpire/ItemManager.java
  src/main/java/io/xpire/commons/core/Messages.java
  src/main/java/io/xpire/logic/Logic.java
  src/main/java/io/xpire/logic/LogicManager.java
  src/main/java/io/xpire/logic/commands/AddCommand.java
  src/main/java/io/xpire/logic/commands/CheckCommand.java
  src/main/java/io/xpire/logic/commands/ClearCommand.java
  src/main/java/io/xpire/logic/commands/DeleteCommand.java
  src/main/java/io/xpire/logic/commands/ExportCommand.java
  src/main/java/io/xpire/logic/commands/RedoCommand.java
  src/main/java/io/xpire/logic/commands/SearchCommand.java
  src/main/java/io/xpire/logic/commands/SetReminderCommand.java
  src/main/java/io/xpire/logic/commands/ShiftToMainCommand.java
  src/main/java/io/xpire/logic/commands/ShiftToReplenishCommand.java
  src/main/java/io/xpire/logic/commands/SortCommand.java
  src/main/java/io/xpire/logic/commands/TagCommand.java
  src/main/java/io/xpire/logic/commands/UndoCommand.java
  src/main/java/io/xpire/logic/commands/ViewCommand.java
  src/main/java/io/xpire/logic/parser/AddCommandParser.java
  src/main/java/io/xpire/logic/parser/DeleteCommandParser.java
  src/main/java/io/xpire/logic/parser/ReplenishParser.java
  src/main/java/io/xpire/logic/parser/SearchCommandParser.java
  src/main/java/io/xpire/logic/parser/TagCommandParser.java
  src/main/java/io/xpire/logic/parser/ViewCommandParser.java
  src/main/java/io/xpire/logic/parser/XpireParser.java
  src/main/java/io/xpire/model/CloneModel.java
  src/main/java/io/xpire/model/ListType.java
  src/main/java/io/xpire/model/Model.java
  src/main/java/io/xpire/model/ModelManager.java
  src/main/java/io/xpire/model/ReplenishList.java
  src/main/java/io/xpire/model/Xpire.java
  src/main/java/io/xpire/model/item/Item.java
  src/main/java/io/xpire/model/item/Quantity.java
  src/main/java/io/xpire/model/item/XpireItem.java
  src/main/java/io/xpire/model/state/FilteredState.java
  src/main/java/io/xpire/model/state/ModifiedState.java
  src/main/java/io/xpire/model/state/StackManager.java
  src/main/java/io/xpire/model/state/State.java
  src/main/java/io/xpire/model/state/StateManager.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/io/xpire/logic/LogicManagerTest.java
  src/test/java/io/xpire/logic/commands/AddCommandIntegrationTest.java
  src/test/java/io/xpire/logic/commands/AddCommandTest.java
  src/test/java/io/xpire/logic/commands/CheckCommandTest.java
  src/test/java/io/xpire/logic/commands/ClearCommandTest.java
  src/test/java/io/xpire/logic/commands/CommandTestUtil.java
  src/test/java/io/xpire/logic/commands/DeleteCommandTest.java
  src/test/java/io/xpire/logic/commands/SearchCommandTest.java
  src/test/java/io/xpire/logic/commands/SetReminderCommandTest.java
  src/test/java/io/xpire/logic/commands/SortCommandTest.java
  src/test/java/io/xpire/logic/commands/TagCommandTest.java
  src/test/java/io/xpire/logic/commands/ViewCommandTest.java
  src/test/java/io/xpire/logic/parser/AddCommandParserTest.java
  src/test/java/io/xpire/logic/parser/SearchCommandParserTest.java
  src/test/java/io/xpire/logic/parser/TagCommandParserTest.java
  src/test/java/io/xpire/logic/parser/XpireParserTest.java
  src/test/java/io/xpire/model/ModelManagerTest.java
  src/test/java/io/xpire/testutil/TestUtil.java
Labels: priority.High

#243 Add PPP
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/OriginalItemCard.png
  docs/images/RetrievePreviousCommandActivityDiagram.png
  docs/images/UiComponentClassDiagram.png
  docs/images/UpdateViewPanelActivityDiagram.png
  docs/team/xiaoyu-nus.adoc
Labels: status.Ongoing
